data_path: ""
item_pattern_file: graph_pattern.txt
item_source_csv: ""
outfiles:
- output_file_name: elements.csv
  label_description_language_list:
  - en
  manage_descriptions: true
  # Note: if no columns to ignore, you must omit the "ignore" key or provide an empty list value: []
  ignore: []
  prop_list:
  - variable: instance_of
    value_type: item
    pid: P1
    qual: []
    ref: []
  - variable: atomic number
    value_type: string
    pid: P15
    qual: []
    ref: []
  - variable: atomic mass
    value_type: string
    pid: P16
    qual: []
    ref: []
  - variable: abbreviation
    value_type: string
    pid: P10
    qual: []
    ref: 
    - variable: reference_url
      value_type: uri
      pid: P4
    - variable: retrieved
      value_type: date
      pid: P8
  - variable: discovery_date
    value_type: date
    pid: P13
    qual: []
    ref: 
    - variable: reference_url
      value_type: uri
      pid: P4
    - variable: retrieved
      value_type: date
      pid: P8
  - variable: phase
    value_type: item
    pid: P14
    qual: []
    ref: 
    - variable: reference_url
      value_type: uri
      pid: P4
    - variable: retrieved
      value_type: date
      pid: P8
