PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX schema: <http://schema.org/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?person ?id ?label ?description ?birthDate ?givenName ?givenNameLabel ?familyName ?familyNameLabel ?gender ?interestedIn ?interestedInLabel ?studies ?studiesLabel ?fieldOfWork ?fieldOfWorkLabel ?occupation ?occupationLabel ?affiliation ?affiliationLabel ?orcidId
WHERE {
  ?person wdt:P108 wd:Q29052.  # use wdt:P69 "educated at" to find students
  ?person rdfs:label ?labelTagged.
  FILTER ( langMatches(lang(?labelTagged),"en" ))
  BIND (str(?labelTagged) AS ?label)

  OPTIONAL {
    ?person skos:altLabel ?altTagged.
    FILTER ( langMatches(lang(?altTagged),"en" ))
    BIND (str(?altTagged) AS ?alt)
  }

  OPTIONAL {
  ?person schema:description ?descriptionTagged.
  FILTER ( langMatches(lang(?descriptionTagged),"en" ))
  BIND (str(?descriptionTagged) AS ?description)
  }

  OPTIONAL {?person wdt:P569 ?birthDate.}

  OPTIONAL {
    ?person wdt:P735 ?givenName.  # note: the values are URIs, not literals.
    ?givenName rdfs:label ?givenNameLabelTagged.
    FILTER ( langMatches(lang(?givenNameLabelTagged),"en" ))
    BIND (str(?givenNameLabelTagged) AS ?givenNameLabel)
  }

  OPTIONAL {
    ?person wdt:P734 ?familyName.
    ?familyName rdfs:label ?familyNameLabelTagged.
    FILTER ( langMatches(lang(?familyNameLabelTagged),"en" ))
    BIND (str(?familyNameLabelTagged) AS ?familyNameLabel)
  }

  OPTIONAL {
    ?person wdt:P21 ?gender.  # note: the values are URIs, not literals.
    ?gender rdfs:label ?genderLabelTagged.
    FILTER ( langMatches(lang(?genderLabelTagged),"en" ))    
    BIND (str(?genderLabelTagged) AS ?genderLabel)
  }

  OPTIONAL {
    ?person wdt:P2650 ?interestedIn.
    ?interestedIn rdfs:label ?interestedInLabelTagged.
    FILTER ( langMatches(lang(?interestedInLabelTagged),"en" ))    
    BIND (str(?interestedInLabelTagged) AS ?interestedInLabel)
  }

  OPTIONAL {
    ?person wdt:P2578 ?studies.
    ?studies rdfs:label ?studiesLabelTagged.
    FILTER ( langMatches(lang(?studiesLabelTagged),"en" ))    
    BIND (str(?studiesLabelTagged) AS ?studiesLabel)
  }

  OPTIONAL {
    ?person wdt:P101 ?fieldOfWork.
    ?fieldOfWork rdfs:label ?fieldOfWorkLabelTagged.
    FILTER ( langMatches(lang(?fieldOfWorkLabelLabelTagged),"en" ))    
    BIND (str(?fieldOfWorkLabelTagged) AS ?fieldOfWorkLabel)
  }

  OPTIONAL {
    ?person wdt:P106 ?occupation.
    ?occupation rdfs:label ?occupationLabelTagged.
    FILTER ( langMatches(lang(?occupationLabelTagged),"en" ))    
    BIND (str(?occupationLabelTagged) AS ?occupationLabel)
  }

  OPTIONAL {
    ?person wdt:P1416 ?affiliation.
    ?affiliation rdfs:label ?affiliationLabelTagged.
    FILTER ( langMatches(lang(?affiliationLabelTagged),"en" ))    
    BIND (str(?affiliationLabelTagged) AS ?affiliationLabel)
  }

  OPTIONAL {
    ?person wdt:P69 ?educatedAt.
    ?educatedAt rdfs:label ?educatedAtLabelTagged.
    FILTER ( langMatches(lang(?educatedAtLabelTagged),"en" ))    
    BIND (str(?educatedAtLabelTagged) AS ?educatedAtLabel)
  }
  OPTIONAL {
    ?person wdt:P496 ?orcidId.
    BIND (URI(CONCAT("http://orcid.org/",?orcidId)) AS ?orcidUri) # turn ORCID string into URI
  }

  BIND (SUBSTR(STR(?person),32) AS ?id) # remove domain name from Wikidata identifier, leaving only the "Q" part
  }